version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    #  - ./data:/data/db

  ports:
      - "27017:27017"

  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
      - "443"
    volumes:
      #- ${HOME}/.aspnet/https:/root/.aspnet/https:ro
      #- ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      